# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_snippet_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text for snippet image')),
                ('background', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background for snippet image')),
                ('snippet_image_field', django_snippet_image.fields.SnippetImageField(blank=True, null=True, snippet_type='default', upload_to='', verbose_name='Example snippet image field')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], max_length=20)),
            ],
            options={
                'verbose_name': 'example object',
                'verbose_name_plural': 'example objects',
            },
        ),
    ]
